name: stable release
on:
  push:
    tags:        
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - name: Patch ab env with run requirements from stable recipe
        uses: mikefarah/yq@master
        with:
          cmd: |
            yq eval-all -i 'select(fi == 0).dependencies += select(fi == 1).requirements.run | select(fi == 0)' ci/conda-envs/ab.yml ci/recipe/stable/meta.yaml
      - name: Set up conda-build environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.9
          activate-environment: build
          environment-file: ci/conda-envs/build.yml
      - name: Build activity-browser stable
        run: |
          conda build ci/recipe/stable
      - name: Upload to anaconda.org
        run: |
          anaconda -t ${{ secrets.CONDA_UPLOAD_TOKEN }} upload \
          /usr/share/miniconda/envs/build/conda-bld/noarch/*.tar.bz2
          anaconda -t ${{ secrets.CONDA_UPLOAD_TOKEN }} upload ci/conda-envs/ab.yml
